### ISSUE TITLE
格式错误

### ISSUE THREAD

**Issue by starryeye-0001** [foxwhite25/qq.py#12]
### 摘要

上次修复的不应该是data['msg_id']

### 复现步骤

在on_guild_channel_update里使用channel.msg_id

### 最小的复现代码

```python
@client.event
async def on_guild_channel_update(old_channel:qq.abc.GuildChannel, channel:qq.abc.GuildChannel):
    global_event_id = channel.msg_id
```

### 预期结果

给出event_id

### 实际结果

给出None

### Intents

default + interaction

### 系统信息

最新GitHub版

### 核对清单

- [X] 我已经搜索了开放的问题，寻找重复的问题。
- [X] 如果有的话，我已经显示了整个 traceback。
- [X] 如果可见的话我已将我的 token 从代码中移除。

### 额外背景

msg_id = msg.get('id')
写错了
是msg_id = data.get('id')
而且希望更新pypi版本，因为我的服务器无法安装github版本qq.py。感谢

**Comment by foxwhite25** [comment]
并没有，msg_id是在ws封包最外层的，不在data里面
