### ISSUE TITLE
运行报错ValueError: mutable default <class 'qq.utils._MissingSentinel'> for field name is not allowed: use default_factory

### ISSUE THREAD

**Issue by zjh4473** [foxwhite25/qq.py#8]
### 摘要

  File "\qq\ext\commands\flags.py", line 65, in <module>     @dataclass      ^^^^^^^^^

### 复现步骤

运行就报错。。。。

### 预期结果

跑起来

### 实际结果

报错：ValueError: mutable default <class 'qq.utils._MissingSentinel'> for field name is not allowed: use default_factory

### Intents

qq.Intents.default()

### 系统信息

- Python v3.11.2-final
- qq.py v1.2.16-beta
    - qq.py pkg_resources: v1.2.16
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621

### 核对清单

- [X] 我已经搜索了开放的问题，寻找重复的问题。
- [X] 如果有的话，我已经显示了整个 traceback。
- [X] 如果可见的话我已将我的 token 从代码中移除。

**Comment by foxwhite25** [comment]
Python 3.11 修改了 dataclass 的使用方法，等我有时间就去修。
你现在用python 3.10就好了

**Comment by foxwhite25** [comment]
这是因为[这个改变](https://docs.python.org/3.11/whatsnew/3.11.html#dataclasses) 。
在 `qq.utils._MissingSentinel` 加入 `__hash__` 就大概能解决这个问题。
